cvConfig:
  class_: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    scoring: r2
    verbose: 3
mlModelsConfig:
  - modelId: svm
    classConstructorConfig:
      class_: SVC
      module: sklearn.svm
      params:
        kernel: poly
        degree: 4
        C: 3
    paramGrid:
      kernel:
        - rbf
        - poly
      C:
        - 1
        - 2
        - 10
  - modelId: random_forest
    classConstructorConfig:
      class_: RandomForestClassifier
      module: sklearn.ensemble
      params:
        max_depth: 10
        n_estimators: 1000
    paramGrid:
      criterion:
        - gini
      max_depth:
        - 5
        - 10
        - 15
      min_impurity_decrease: 0.2
  - modelId: logistic_reg
    classConstructorConfig:
      class_: LogisticRegression
      module: sklearn.linear_model
